#!/usr/bin/env ruby
#
# % episozip [-P episopassのHTML] out.zip file1 file2
#

path = "#{__dir__}/../data/sample.html" # gemのファイル指定する方法は?
localpath = File.expand_path("~/.episopass.html")
path = localpath if File.exist?(localpath)

if ARGV[0] == "-P"
  path = ARGV[1]
  ARGV.shift 2
end

html = ''
if path =~ /^http/
  html = Net::HTTP.get(URI.parse(arg))
elsif File.exist?(path)
  html = File.read(path)
end

if html == ''
  STDERR.puts "EpisoPass問題(#{path})がみつかりません"
  exit
end

dir = "/tmp/EpisoPassDir#{$$}"
if File.exist?(dir)
  STDERR.puts "もう一度試してください"
  exit
end

system "mkdir #{dir}"

File.open("#{dir}/episopass.html","w"){ |f|
  f.print html
}

zipfile = ARGV.shift
if !zipfile
  STDERR.puts "出力ファイル名を指定してください"
  system "/bin/rm -r #{dir}"
  exit
end
if zipfile !~ /\.zip$/
  STDERR.puts "出力ファイルの拡張子は.zipにしてください"
  system "/bin/rm -r #{dir}"
  exit
end
if File.exist?(zipfile)
  STDERR.puts "#{zipfile}が既に存在します"
  system "/bin/rm -r #{dir}"
  exit
end

system "zip -e -P `episopass #{dir}/episopass.html` #{dir}/episopass.zip #{ARGV.join(' ')}"

system "cd #{dir} ; zip out.zip episopass.zip episopass.html"
system "/bin/mv #{dir}/out.zip #{zipfile}"
system "/bin/rm -r #{dir}"
